name: image_compression
description: A Dart Extension for image package to compress and resize the images.
version: 1.0.3
homepage: https://github.com/eyro-labs/image_compression

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image: ^4.0.15 
  mime: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
